### ISSUE TITLE
Check for computational complexity of code and see how it can be reduced

### ISSUE THREAD

**Issue by masonhargrave** [braingeneers/organoid-simulation#2]
In particular, look at the numpy masking and see if that can be done more simply.

**Comment by atspaeth** [comment]
I just pushed a 9x speed boost using the idea I mentioned yesterday. I think it's O(n^2) because it's vectorized (n products of n things each, basically), but I decreased a few n^2 things to mn where m is proportional to but smaller than n, e.g. the number of just excitatory cells or the number of cells that were active last timestep.
